### ISSUE TITLE
Typo on Yellow Get Started Guide

### ISSUE THREAD

**Issue by BGFHA** [home-assistant/yellow.home-assistant.io#131]
On the "Getting Started Home Assistant Yellow Kit with NVMe" (https://yellow.home-assistant.io/power-supply-nvme/), in section "[Installing the NVMe drive](https://yellow.home-assistant.io/power-supply-nvme/#installing-the-nvme-drive)" in "Step 2 Inserting the drive" the 2nd paragraph read "Carefully hold the **_NMVe_** M.2 SSD by the sides.", rather than "Carefully hold the **_NVMe_** M.2 SSD by the sides."

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @BGFHA :muscle:
