### ISSUE TITLE
Cannot Copy Data to NVME

### ISSUE THREAD

**Issue by custa1200** [home-assistant/yellow.home-assistant.io#134]
Not sure if you guys are on the lookout for issues, but this seems to be a bit of a show stopper fr people who have just received their POE kits in the past couple of weeks (me included :( ).I would rather do it in a supported way rather than dropping out to the terminal.

https://community.home-assistant.io/t/unable-to-move-datadisk-to-nvme-on-yellow-poe-kit/553508

**Comment by agners** [comment]
This is fixed with Supervisor 2023.04.0 release.
