### ISSUE TITLE
Failed to forcing installation onto the NVMe SSD

### ISSUE THREAD

**Issue by xavier-wong-hk** [home-assistant/yellow.home-assistant.io#194]
Just got my yellow, CM4 with 32GB eMMC (CM4108032) and Kingsman KM600 128GB NVMe installed
Boot up with USB installer and waited for yellow light up constantly. Press the blue button.
After onboarding, everything still install on eMMC in cm4, 128GB NVMc can only be a data disk. 
Any idea which step was wrong ?

**Comment by xavier-wong-hk** [comment]
This is the log file while installing 
[putty.log](https://github.com/home-assistant/yellow.home-assistant.io/files/12740843/putty.log)

**Comment by agners** [comment]
Sorry for the delay. This indeed seems to be a bug in the latest Yellow installer :cry: 

I am working on a new release.

**Comment by max** [comment]
Thanks, @agners. Is there an issue we can watch to see when this is resolved?

**Comment by agners** [comment]
@xavier-wong-hk @max there is now a new installer version 2023-10-25 available through the Raspberry Pi Imager. With this release flashing to NVMe directly will work again.

@urbaniak you can't move the OS once it is installed. So if you want to move the whole OS, you'll need to reinstall the OS with the new Imager menetioned above (you should be able to use [Method 1 documented here](https://yellow.home-assistant.io/guides/reinstall-os/) to install it again).

**Comment by max** [comment]
I can confirm that the new installer works. Thanks, @agners.
