### ISSUE TITLE
RPi Imager screenshots/instructions are out of date

### ISSUE THREAD

**Issue by strugee** [home-assistant/yellow.home-assistant.io#201]
On my Raspberry Pi Imager 1.8.1 (installed through Flathub), there is now a selector for "Raspberry Pi device". (I've selected something, but there is no default.)

![image](https://github.com/home-assistant/yellow.home-assistant.io/assets/911174/8dc5d239-b64e-45fa-a51e-4dfdc7cf094c)

**Comment by c0ffeeca7** [comment]
Thank you for the catch, @strugee :+1:
